global:
  checkNewVersion: true
  sendAnonymousUsage: false

entryPoints:
  web:
    address: :80

    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

log:
  level: DEBUG

api: 
  insecure: true

providers:
  docker: 
    exposedByDefault: false
    network: client-side
    