/*
 * OIDC ICT Userinfo Endpoint
 *
 * Endpoint for OpenID Connect's ID Certifcation Token endpoint for userinfo.
 *
 * API version: 0.4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package ict

type EcSigningAlgorithm string

// List of EcSigningAlgorithms
const (
	ES256 EcSigningAlgorithm = "ES256"
	ES384 EcSigningAlgorithm = "ES384"
	ES512 EcSigningAlgorithm = "ES512"
)
