/*
 * OIDC ID Certifcation Token Userinfo Endpoint
 *
 * Endpoint for OpenID Connect's ID Certifcation Token endpoint for userinfo.
 *
 * API version: 0.4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package ict

type EdSigningAlgorithm string

// List of EdSigningAlgorithm
const (
	ED_DSA EdSigningAlgorithm = "EdDSA"
)
