/*
 * OIDC ICT Userinfo Endpoint
 *
 * Endpoint for OpenID Connect's ID Certifcation Token endpoint for userinfo.
 *
 * API version: 0.4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package ict

type IctResponse struct {
	IdCertificationToken string `json:"id_certification_token"`
	// Number of seconds until the ID Certifcation Token expires.
	ExpiresIn int32 `json:"expires_in,omitempty"`
	// Space delimited claims provided in the ID Certifcation Token.
	Claims string `json:"claims,omitempty"`
}
