/*
 * OIDC ICT Userinfo Endpoint
 *
 * Endpoint for OpenID Connect's ID Certifcation Token endpoint for userinfo.
 *
 * API version: 0.4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package ict

// Information about ocurred error.
type ErrorStatus struct {
	// Status Code
	Code int `json:"code"`
	// Status Text
	Status string `json:"status"`
	// More detailed description
	Description string `json:"description,omitempty"`
}
