/*
 * OIDC ICT Userinfo Endpoint
 *
 * Endpoint for OpenID Connect's ID Certifcation Token endpoint for userinfo.
 *
 * API version: 0.4.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package ict

import (
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

func NewRouter() *chi.Mux {
	mux := chi.NewMux()
	// Logs the start and end of each request with the elapsed processing time
	mux.Use(middleware.Logger)
	// Injects a request ID into the context of each request
	mux.Use(middleware.RequestID)
	// Gracefully absorb panics and prints the stack trace
	mux.Use(middleware.Recoverer)
	// Redirect trailing slashes
	mux.Use(middleware.RedirectSlashes)

	mux.Options("/", IctOptions)
	mux.Post("/", GenICT)
	return mux
}
